### ISSUE TITLE
OSError: [Errno 8] Exec format error:

### ISSUE THREAD

**Issue by andresberejnoi** [alectrocute/flaskSaaS#6]
Hello, I am trying to build the project on Ubuntu 18.04 and I am getting an error when trying to launch the server with the command `python manage.py runserver`. The project was built successfully and I am using Python 3 with conda and a virtual environment. The full error I get is the following:

```sh
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    manager.run()
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/site-packages/flask_script/commands.py", line 425, in __call__
    **self.server_options)
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/site-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/site-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/username/miniconda3/envs/myenv/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

Do you have any idaa of what could be wrong?

**Comment by andresberejnoi** [comment]
I am not sure what happened, but I simply deleted the whole repository and cloned it again with git clone. After that, I followed the steps in the README file and did not have any issues this time.
