### ISSUE TITLE
OSError: [Errno 8] Exec format error:

### ISSUE THREAD

**Issue by rjunderwood** [alectrocute/flaskSaaS#7]
When running:
python manage.py runserver
this error. PLEASE HELP.

* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    manager.run()
  File "/mnt/c/Users/riley/alrye/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/mnt/c/Users/riley/alrye/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/mnt/c/Users/riley/alrye/lib/python3.6/site-packages/flask_script/commands.py", line 425, in __call__
    **self.server_options)
  File "/mnt/c/Users/riley/alrye/lib/python3.6/site-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/mnt/c/Users/riley/alrye/lib/python3.6/site-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/mnt/c/Users/riley/alrye/lib/python3.6/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader    sys.exit(reloader.restart_with_reloader())
  File "/mnt/c/Users/riley/alrye/lib/python3.6/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/mnt/c/Users/riley/Desktop/2019/ALRYE/test/flaskSaaS/manage.py'

**Comment by medicalnp** [comment]
Had a similar issue using cygwin on windows, did you find a solution?

**Comment by FurkanArslan** [comment]
I have a similar problem in macOS 10.12. Is there any solution for this problem?

**Comment by pyl0ne** [comment]
@FurkanArslan same problem same OS 10.12.6

**Comment by alexlaurence** [comment]
Same issue

**Comment by alexlaurence** [comment]
FOUND THE SOLUTION. Install Docker. Omg. Author forgot about that...

**Comment by MrCoca** [comment]
> FOUND THE SOLUTION. Install Docker. Omg. Author forgot about that...

Hi Alex, How did you configure Docker?  do you have any documents that i can look at for the configuration of Docker. Thanks.

**Comment by donnybert** [comment]
I'm having this problem too and I have installed docker, but I too don't know how to configure it the way you did to make it work. Could you elaborate?
