### ISSUE TITLE
ImportError: cannot import name 'getargspec'

### ISSUE THREAD

**Issue by yingwang131** [alectrocute/flaskSaaS#8]
Do you guys have this problem? I have python 3, and should I run the program on python 2?

C:\Users\ying\Downloads\flaskSaaS-master\flaskSaaS-master>python manage.py initdb
Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    manager.run()
  File "C:\Users\ying\AppData\Roaming\Python\Python35\site-packages\flask_script\__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "C:\Users\ying\AppData\Roaming\Python\Python35\site-packages\flask_script\__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "C:\Users\ying\AppData\Roaming\Python\Python35\site-packages\flask_script\commands.py", line 215, in __call__
    with app.test_request_context():
  File "C:\Users\ying\AppData\Roaming\Python\Python35\site-packages\flask\app.py", line 1780, in test_request_context
    from flask.testing import make_test_environ_builder
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\testing.py", line 17, in <module>
    from flask.cli import ScriptInfo
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\cli.py", line 29, in <module>
    from ._compat import getargspec, iteritems, reraise, text_type
ImportError: cannot import name 'getargspec'

C:\Users\ying\Downloads\flaskSaaS-master\flaskSaaS-master>python --version
Python 3.5.6 :: Anaconda, Inc.

**Comment by andresberejnoi** [comment]
I am running it with python 3.7.3 that comes with miniconda and have no problems. I am using Ubuntu 18.04 though
